-- =====================================================================
-- HỆ THỐNG QUẢN LÝ THƯ VIỆN SỐ - ORACLE DATABASE 19c
-- Chuyển đổi từ SQL Server 2016+ sang Oracle 19c
-- Schema/User: THUVIENSO
-- Service: ORCL - Port: 1521
-- =====================================================================

-- KẾT NỐI BẰNG USER THUVIENSO TRƯỚC KHI CHẠY FILE NÀY.
-- Oracle không dùng CREATE DATABASE / USE như SQL Server.

PROMPT [1/3] RESET CAC OBJECT CU CUA DU AN...

-- =====================================================================
-- 0. XÓA OBJECT CŨ
-- =====================================================================

BEGIN
  FOR r IN (
    SELECT object_name, object_type
    FROM user_objects
    WHERE object_name IN (
      'SP_THONGKETONGHOP','SP_QUETNHACHANTRA','SP_CAPNHATKETQUAEMAIL',
      'SP_HUYDANGKYHETHAN','SP_DUYETYEUCAUDATMUA','SP_GUIYEUCAUDATMUA',
      'SP_GHINHANTRASACH','SP_LAPPHIEUMUON','SP_DANGKYMUON','SP_GHILUOTTAI','SP_XACTHUCMATHE',
      'VW_TINHTRANGMUON','VW_PHIEUQUAHAN','VW_TONKHO',
      'UX_THE_MOTTHEHOATDONG','UX_TAIKHOAN_DOCGIA','UX_TAIKHOAN_THUTHU',
      'UX_DK_BANSAODANGGIU','UX_DK_THETAILIEU','UX_PM_BANSAODANGMUON',
      'UX_PM_DANGKY','IX_PM_HANTRA_MO','IX_PM_THE','IX_LUOTTAI_THOIDIEM',
      'IX_YC_TRANGTHAI'
    )
  )
  LOOP
    BEGIN
      IF r.object_type = 'PROCEDURE' THEN
        EXECUTE IMMEDIATE 'DROP PROCEDURE ' || r.object_name;
      ELSIF r.object_type = 'VIEW' THEN
        EXECUTE IMMEDIATE 'DROP VIEW ' || r.object_name;
      ELSIF r.object_type = 'INDEX' THEN
        EXECUTE IMMEDIATE 'DROP INDEX ' || r.object_name;
      END IF;
    EXCEPTION
      WHEN OTHERS THEN NULL;
    END;
  END LOOP;
END;
/

BEGIN
  FOR r IN (
    SELECT table_name
    FROM user_tables
    WHERE table_name IN (
      'NHATKYLAPLICH','EMAILNHACHAN','YEUCAUDATMUA','LUOTTAI',
      'PHIEUMUON','DANGKYMUON','BANSAO','TEPDIENTU','TAILIEU_TACGIA',
      'TAILIEU','NHAXUATBAN','TACGIA','CHUDE','TAIKHOAN','THETHUVIEN',
      'DOCGIA','THUTHU'
    )
  )
  LOOP
    BEGIN
      EXECUTE IMMEDIATE
        'DROP TABLE ' || r.table_name || ' CASCADE CONSTRAINTS PURGE';
    EXCEPTION
      WHEN OTHERS THEN NULL;
    END;
  END LOOP;
END;
/

-- =====================================================================
-- 1. NHÓM NGƯỜI DÙNG
-- =====================================================================

CREATE TABLE ThuThu (
    MaThuThu      VARCHAR2(10)   NOT NULL,
    HoTen         NVARCHAR2(100) NOT NULL,
    Email         VARCHAR2(100)  NOT NULL,
    SoDienThoai   VARCHAR2(15),
    ChucVu        NVARCHAR2(50)  DEFAULT N'Thủ thư' NOT NULL,
    DangLamViec   NUMBER(1)      DEFAULT 1 NOT NULL,
    CONSTRAINT PK_ThuThu PRIMARY KEY (MaThuThu),
    CONSTRAINT UQ_ThuThu_Email UNIQUE (Email),
    CONSTRAINT CK_ThuThu_DangLamViec CHECK (DangLamViec IN (0,1))
);

CREATE TABLE DocGia (
    MaDocGia      VARCHAR2(10)   NOT NULL,
    HoTen         NVARCHAR2(100) NOT NULL,
    LoaiDocGia    VARCHAR2(10)   NOT NULL,
    DonVi         NVARCHAR2(100),
    NgaySinh      DATE,
    Email         VARCHAR2(100)  NOT NULL,
    SoDienThoai   VARCHAR2(15),
    NgayTao       TIMESTAMP(0)   DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_DocGia PRIMARY KEY (MaDocGia),
    CONSTRAINT UQ_DocGia_Email UNIQUE (Email),
    CONSTRAINT CK_DocGia_Loai
      CHECK (LoaiDocGia IN ('GiangVien','NhanVien','SinhVien')),
    CONSTRAINT CK_DocGia_Email
      CHECK (Email LIKE '%_@_%._%')
);

CREATE TABLE TheThuVien (
    MaThe        VARCHAR2(12) NOT NULL,
    MaDocGia     VARCHAR2(10) NOT NULL,
    NgayCap      DATE NOT NULL,
    HanSuDung    DATE NOT NULL,
    TrangThai    VARCHAR2(10) DEFAULT 'HoatDong' NOT NULL,
    CONSTRAINT PK_TheThuVien PRIMARY KEY (MaThe),
    CONSTRAINT FK_The_DocGia
      FOREIGN KEY (MaDocGia) REFERENCES DocGia(MaDocGia),
    CONSTRAINT CK_The_TrangThai
      CHECK (TrangThai IN ('HoatDong','HetHan','Khoa','Mat')),
    CONSTRAINT CK_The_Han CHECK (HanSuDung > NgayCap)
);

-- SQL Server filtered unique index:
-- WHERE TrangThai = 'HoatDong'
-- -> Oracle function-based unique index.
CREATE UNIQUE INDEX UX_The_MotTheHoatDong
ON TheThuVien (CASE WHEN TrangThai = 'HoatDong' THEN MaDocGia END);

CREATE TABLE TaiKhoan (
    MaTaiKhoan       NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    TenDangNhap      VARCHAR2(50) NOT NULL,
    MatKhauHash      RAW(32) NOT NULL,
    MatKhauSalt      RAW(16) NOT NULL,
    VaiTro           VARCHAR2(10) NOT NULL,
    MaDocGia         VARCHAR2(10),
    MaThuThu         VARCHAR2(10),
    TrangThai        VARCHAR2(10) DEFAULT 'HoatDong' NOT NULL,
    SoLanSaiLienTiep NUMBER(3) DEFAULT 0 NOT NULL,
    NgayTao          TIMESTAMP(0) DEFAULT SYSTIMESTAMP NOT NULL,
    LanDangNhapCuoi  TIMESTAMP(0),
    CONSTRAINT PK_TaiKhoan PRIMARY KEY (MaTaiKhoan),
    CONSTRAINT UQ_TaiKhoan_Ten UNIQUE (TenDangNhap),
    CONSTRAINT FK_TaiKhoan_DocGia
      FOREIGN KEY (MaDocGia) REFERENCES DocGia(MaDocGia),
    CONSTRAINT FK_TaiKhoan_ThuThu
      FOREIGN KEY (MaThuThu) REFERENCES ThuThu(MaThuThu),
    CONSTRAINT CK_TaiKhoan_VaiTro
      CHECK (VaiTro IN ('DocGia','ThuThu')),
    CONSTRAINT CK_TaiKhoan_TrangThai
      CHECK (TrangThai IN ('HoatDong','TamKhoa')),
    CONSTRAINT CK_TaiKhoan_SoLanSai
      CHECK (SoLanSaiLienTiep BETWEEN 0 AND 255),
    CONSTRAINT CK_TaiKhoan_ChuSoHuu CHECK (
      (VaiTro = 'DocGia' AND MaDocGia IS NOT NULL AND MaThuThu IS NULL)
      OR
      (VaiTro = 'ThuThu' AND MaThuThu IS NOT NULL AND MaDocGia IS NULL)
    )
);

CREATE UNIQUE INDEX UX_TaiKhoan_DocGia
ON TaiKhoan (CASE WHEN MaDocGia IS NOT NULL THEN MaDocGia END);

CREATE UNIQUE INDEX UX_TaiKhoan_ThuThu
ON TaiKhoan (CASE WHEN MaThuThu IS NOT NULL THEN MaThuThu END);

-- =====================================================================
-- 2. NHÓM DANH MỤC TÀI LIỆU
-- =====================================================================

CREATE TABLE ChuDe (
    MaChuDe  VARCHAR2(10) NOT NULL,
    TenChuDe NVARCHAR2(100) NOT NULL,
    MoTa     NVARCHAR2(255),
    CONSTRAINT PK_ChuDe PRIMARY KEY (MaChuDe),
    CONSTRAINT UQ_ChuDe_Ten UNIQUE (TenChuDe)
);

CREATE TABLE TacGia (
    MaTacGia  VARCHAR2(10) NOT NULL,
    TenTacGia NVARCHAR2(100) NOT NULL,
    GhiChu    NVARCHAR2(255),
    CONSTRAINT PK_TacGia PRIMARY KEY (MaTacGia)
);

CREATE TABLE NhaXuatBan (
    MaNXB       VARCHAR2(10) NOT NULL,
    TenNXB      NVARCHAR2(150) NOT NULL,
    DiaChi      NVARCHAR2(255),
    SoDienThoai VARCHAR2(15),
    CONSTRAINT PK_NhaXuatBan PRIMARY KEY (MaNXB),
    CONSTRAINT UQ_NXB_Ten UNIQUE (TenNXB)
);

CREATE TABLE TaiLieu (
    MaTaiLieu   VARCHAR2(10) NOT NULL,
    TenTaiLieu  NVARCHAR2(255) NOT NULL,
    LoaiTaiLieu VARCHAR2(10) NOT NULL,
    HinhThuc    VARCHAR2(6) NOT NULL,
    MaChuDe     VARCHAR2(10) NOT NULL,
    MaNXB       VARCHAR2(10),
    NamXuatBan  NUMBER(5) NOT NULL,
    MoTa        NVARCHAR2(1000),
    NgayTao     TIMESTAMP(0) DEFAULT SYSTIMESTAMP NOT NULL,
    NgayCapNhat TIMESTAMP(0),
    CONSTRAINT PK_TaiLieu PRIMARY KEY (MaTaiLieu),
    CONSTRAINT FK_TaiLieu_ChuDe
      FOREIGN KEY (MaChuDe) REFERENCES ChuDe(MaChuDe),
    CONSTRAINT FK_TaiLieu_NXB
      FOREIGN KEY (MaNXB) REFERENCES NhaXuatBan(MaNXB),
    CONSTRAINT CK_TaiLieu_Loai
      CHECK (LoaiTaiLieu IN ('Sach','Bao','TapChi','NgheNhin')),
    CONSTRAINT CK_TaiLieu_HinhThuc
      CHECK (HinhThuc IN ('BanIn','DienTu','CaHai')),
    CONSTRAINT CK_TaiLieu_Nam
      CHECK (NamXuatBan BETWEEN 1800 AND 2100)
);

CREATE TABLE TaiLieu_TacGia (
    MaTaiLieu VARCHAR2(10) NOT NULL,
    MaTacGia  VARCHAR2(10) NOT NULL,
    ThuTu     NUMBER(3) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_TaiLieu_TacGia PRIMARY KEY (MaTaiLieu, MaTacGia),
    CONSTRAINT FK_TLTG_TaiLieu
      FOREIGN KEY (MaTaiLieu) REFERENCES TaiLieu(MaTaiLieu) ON DELETE CASCADE,
    CONSTRAINT FK_TLTG_TacGia
      FOREIGN KEY (MaTacGia) REFERENCES TacGia(MaTacGia)
);

CREATE TABLE TepDienTu (
    MaTaiLieu   VARCHAR2(10) NOT NULL,
    DuongDanTep NVARCHAR2(400) NOT NULL,
    DinhDang    VARCHAR2(5) NOT NULL,
    DungLuongMB NUMBER(8,2) NOT NULL,
    ChoPhepTai  NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_TepDienTu PRIMARY KEY (MaTaiLieu),
    CONSTRAINT FK_Tep_TaiLieu
      FOREIGN KEY (MaTaiLieu) REFERENCES TaiLieu(MaTaiLieu) ON DELETE CASCADE,
    CONSTRAINT CK_Tep_DinhDang
      CHECK (DinhDang IN ('PDF','EPUB','MP3','MP4')),
    CONSTRAINT CK_Tep_DungLuong CHECK (DungLuongMB > 0),
    CONSTRAINT CK_Tep_ChoPhepTai CHECK (ChoPhepTai IN (0,1))
);

CREATE TABLE BanSao (
    MaBanSao  VARCHAR2(10) NOT NULL,
    MaTaiLieu VARCHAR2(10) NOT NULL,
    ViTriKe   VARCHAR2(10),
    NgayNhap  DATE DEFAULT SYSDATE NOT NULL,
    TinhTrang VARCHAR2(10) DEFAULT 'SanSang' NOT NULL,
    GhiChu    NVARCHAR2(255),
    CONSTRAINT PK_BanSao PRIMARY KEY (MaBanSao),
    CONSTRAINT FK_BanSao_TaiLieu
      FOREIGN KEY (MaTaiLieu) REFERENCES TaiLieu(MaTaiLieu),
    CONSTRAINT CK_BanSao_TinhTrang
      CHECK (TinhTrang IN
        ('SanSang','DangGiu','DangMuon','CanKiemTra','Mat','ThanhLy'))
);

-- =====================================================================
-- 3. NHÓM NGHIỆP VỤ
-- =====================================================================

CREATE TABLE DangKyMuon (
    Id           NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    MaDangKy     VARCHAR2(8)
                 GENERATED ALWAYS AS
                 (CAST('DK' || LPAD(TO_CHAR(Id),6,'0') AS VARCHAR2(8))) VIRTUAL,
    MaThe        VARCHAR2(12) NOT NULL,
    MaTaiLieu    VARCHAR2(10) NOT NULL,
    MaBanSaoGiu  VARCHAR2(10) NOT NULL,
    NgayDangKy   TIMESTAMP(0) DEFAULT SYSTIMESTAMP NOT NULL,
    HanNhan      DATE NOT NULL,
    TrangThai    VARCHAR2(8) DEFAULT 'ChoNhan' NOT NULL,
    CONSTRAINT PK_DangKyMuon PRIMARY KEY (Id),
    CONSTRAINT UQ_DK_Ma UNIQUE (MaDangKy),
    CONSTRAINT FK_DK_The
      FOREIGN KEY (MaThe) REFERENCES TheThuVien(MaThe),
    CONSTRAINT FK_DK_TaiLieu
      FOREIGN KEY (MaTaiLieu) REFERENCES TaiLieu(MaTaiLieu),
    CONSTRAINT FK_DK_BanSao
      FOREIGN KEY (MaBanSaoGiu) REFERENCES BanSao(MaBanSao),
    CONSTRAINT CK_DK_TrangThai
      CHECK (TrangThai IN ('ChoNhan','DaNhan','DaHuy','HetHan')),
    CONSTRAINT CK_DK_HanNhan
      CHECK (HanNhan >= TRUNC(CAST(NgayDangKy AS DATE)))
);

CREATE UNIQUE INDEX UX_DK_BanSaoDangGiu
ON DangKyMuon (CASE WHEN TrangThai = 'ChoNhan' THEN MaBanSaoGiu END);

CREATE UNIQUE INDEX UX_DK_TheTaiLieu
ON DangKyMuon (
  CASE WHEN TrangThai = 'ChoNhan' THEN MaThe END,
  CASE WHEN TrangThai = 'ChoNhan' THEN MaTaiLieu END
);

CREATE TABLE PhieuMuon (
    Id           NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    MaPhieuMuon  VARCHAR2(8)
                 GENERATED ALWAYS AS
                 (CAST('PM' || LPAD(TO_CHAR(Id),6,'0') AS VARCHAR2(8))) VIRTUAL,
    MaThe        VARCHAR2(12) NOT NULL,
    MaBanSao     VARCHAR2(10) NOT NULL,
    DangKyId     NUMBER(10),
    MaThuThuLap  VARCHAR2(10) NOT NULL,
    NgayMuon     DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
    HanTra       DATE NOT NULL,
    NgayTra      DATE,
    MaThuThuNhan VARCHAR2(10),
    TrangThai    VARCHAR2(10) DEFAULT 'DangMuon' NOT NULL,
    SoNgayTre    NUMBER(10) DEFAULT 0 NOT NULL,
    GhiChu       NVARCHAR2(255),
    CONSTRAINT PK_PhieuMuon PRIMARY KEY (Id),
    CONSTRAINT UQ_PM_Ma UNIQUE (MaPhieuMuon),
    CONSTRAINT FK_PM_The
      FOREIGN KEY (MaThe) REFERENCES TheThuVien(MaThe),
    CONSTRAINT FK_PM_BanSao
      FOREIGN KEY (MaBanSao) REFERENCES BanSao(MaBanSao),
    CONSTRAINT FK_PM_DangKy
      FOREIGN KEY (DangKyId) REFERENCES DangKyMuon(Id),
    CONSTRAINT FK_PM_ThuThuLap
      FOREIGN KEY (MaThuThuLap) REFERENCES ThuThu(MaThuThu),
    CONSTRAINT FK_PM_ThuThuNhan
      FOREIGN KEY (MaThuThuNhan) REFERENCES ThuThu(MaThuThu),
    CONSTRAINT CK_PM_TrangThai
      CHECK (TrangThai IN ('DangMuon','DaTra','TraHuHong','Mat')),
    CONSTRAINT CK_PM_SoNgayTre CHECK (SoNgayTre >= 0),
    CONSTRAINT CK_PM_HanTra CHECK (HanTra >= NgayMuon),
    CONSTRAINT CK_PM_NgayTra
      CHECK (NgayTra IS NULL OR NgayTra >= NgayMuon),
    CONSTRAINT CK_PM_DongPhieu CHECK (
      TrangThai = 'DangMuon'
      OR (NgayTra IS NOT NULL AND MaThuThuNhan IS NOT NULL)
    ),
    CONSTRAINT CK_PM_GhiChu CHECK (
      TrangThai NOT IN ('TraHuHong','Mat')
      OR TRIM(GhiChu) IS NOT NULL   -- Oracle: '' = NULL nên phải kiểm tra IS NOT NULL
    )
);

CREATE UNIQUE INDEX UX_PM_BanSaoDangMuon
ON PhieuMuon (CASE WHEN TrangThai = 'DangMuon' THEN MaBanSao END);

CREATE UNIQUE INDEX UX_PM_DangKy
ON PhieuMuon (CASE WHEN DangKyId IS NOT NULL THEN DangKyId END);

-- SQL Server INCLUDE/filtered index -> Oracle index thông thường.
CREATE INDEX IX_PM_HanTra_Mo
ON PhieuMuon(HanTra, MaThe, MaBanSao);

CREATE INDEX IX_PM_The
ON PhieuMuon(MaThe, TrangThai);

CREATE TABLE LuotTai (
    Id         NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    MaTaiLieu  VARCHAR2(10) NOT NULL,
    MaThe      VARCHAR2(12) NOT NULL,
    ThoiDiem   TIMESTAMP(0) DEFAULT SYSTIMESTAMP NOT NULL,
    DiaChiIP   VARCHAR2(45),
    CONSTRAINT PK_LuotTai PRIMARY KEY (Id),
    CONSTRAINT FK_LuotTai_Tep
      FOREIGN KEY (MaTaiLieu) REFERENCES TepDienTu(MaTaiLieu),
    CONSTRAINT FK_LuotTai_The
      FOREIGN KEY (MaThe) REFERENCES TheThuVien(MaThe)
);

CREATE INDEX IX_LuotTai_ThoiDiem
ON LuotTai(ThoiDiem, MaTaiLieu);

CREATE TABLE YeuCauDatMua (
    Id               NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    MaYeuCau         VARCHAR2(8)
                     GENERATED ALWAYS AS
                     (CAST('YC' || LPAD(TO_CHAR(Id),6,'0') AS VARCHAR2(8))) VIRTUAL,
    MaTaiKhoan       NUMBER(10) NOT NULL,
    TenSach          NVARCHAR2(255) NOT NULL,
    TacGia           NVARCHAR2(150) NOT NULL,
    NamXuatBan       NUMBER(5) NOT NULL,
    NhaXuatBan       NVARCHAR2(150),
    LyDoDeNghi       NVARCHAR2(500),
    NgayGui          TIMESTAMP(0) DEFAULT SYSTIMESTAMP NOT NULL,
    TrangThai        VARCHAR2(8) DEFAULT 'ChoDuyet' NOT NULL,
    MaThuThuDuyet    VARCHAR2(10),
    NgayDuyet        TIMESTAMP(0),
    KetQuaGhiChu     NVARCHAR2(500),
    MaTaiLieuLienKet VARCHAR2(10),
    CONSTRAINT PK_YeuCauDatMua PRIMARY KEY (Id),
    CONSTRAINT UQ_YC_Ma UNIQUE (MaYeuCau),
    CONSTRAINT FK_YC_TaiKhoan
      FOREIGN KEY (MaTaiKhoan) REFERENCES TaiKhoan(MaTaiKhoan),
    CONSTRAINT FK_YC_ThuThu
      FOREIGN KEY (MaThuThuDuyet) REFERENCES ThuThu(MaThuThu),
    CONSTRAINT FK_YC_TaiLieu
      FOREIGN KEY (MaTaiLieuLienKet) REFERENCES TaiLieu(MaTaiLieu),
    CONSTRAINT CK_YC_TenSach
      CHECK (LENGTH(TRIM(TenSach)) > 0),
    CONSTRAINT CK_YC_TacGia
      CHECK (LENGTH(TRIM(TacGia)) > 0),
    CONSTRAINT CK_YC_Nam
      CHECK (NamXuatBan BETWEEN 1800 AND 2100),
    CONSTRAINT CK_YC_TrangThai
      CHECK (TrangThai IN ('ChoDuyet','ChapNhan','TuChoi')),
    CONSTRAINT CK_YC_DaDuyet CHECK (
      TrangThai = 'ChoDuyet'
      OR (MaThuThuDuyet IS NOT NULL AND NgayDuyet IS NOT NULL)
    ),
    CONSTRAINT CK_YC_LyDoTuChoi CHECK (
      TrangThai <> 'TuChoi'
      OR TRIM(KetQuaGhiChu) IS NOT NULL
    )
);

CREATE INDEX IX_YC_TrangThai
ON YeuCauDatMua(TrangThai, NgayGui);

CREATE TABLE EmailNhacHan (
    Id           NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    MaEmail      VARCHAR2(8)
                 GENERATED ALWAYS AS
                 (CAST('EM' || LPAD(TO_CHAR(Id),6,'0') AS VARCHAR2(8))) VIRTUAL,
    PhieuMuonId  NUMBER(10) NOT NULL,
    DiaChiNhan   VARCHAR2(100) NOT NULL,
    TieuDe       NVARCHAR2(200) NOT NULL,
    NoiDung      CLOB NOT NULL,
    ThoiDiemTao  TIMESTAMP(0) DEFAULT SYSTIMESTAMP NOT NULL,
    ThoiDiemGui  TIMESTAMP(0),
    TrangThai    VARCHAR2(6) DEFAULT 'ChoGui' NOT NULL,
    SoLanThu     NUMBER(3) DEFAULT 0 NOT NULL,
    LoiGanNhat   NVARCHAR2(500),
    CONSTRAINT PK_EmailNhacHan PRIMARY KEY (Id),
    CONSTRAINT UQ_Email_Ma UNIQUE (MaEmail),
    CONSTRAINT FK_Email_PhieuMuon
      FOREIGN KEY (PhieuMuonId) REFERENCES PhieuMuon(Id),
    CONSTRAINT UQ_Email_Phieu UNIQUE (PhieuMuonId),
    CONSTRAINT CK_Email_TrangThai
      CHECK (TrangThai IN ('ChoGui','DaGui','Loi')),
    CONSTRAINT CK_Email_SoLanThu
      CHECK (SoLanThu BETWEEN 0 AND 3)
);

CREATE TABLE NhatKyLapLich (
    Id            NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    TenCongViec   VARCHAR2(50) NOT NULL,
    BatDau        TIMESTAMP(0) NOT NULL,
    KetThuc       TIMESTAMP(0),
    SoBanGhiQuet  NUMBER(10) DEFAULT 0 NOT NULL,
    SoThanhCong   NUMBER(10) DEFAULT 0 NOT NULL,
    SoLoi          NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_NhatKyLapLich PRIMARY KEY (Id)
);

-- =====================================================================
-- 4. VIEW
-- =====================================================================

CREATE OR REPLACE VIEW vw_TonKho AS
SELECT
    tl.MaTaiLieu,
    tl.TenTaiLieu,
    tl.HinhThuc,
    SUM(CASE WHEN bs.TinhTrang = 'SanSang' THEN 1 ELSE 0 END) AS SoLuongTon,
    SUM(CASE WHEN bs.TinhTrang = 'DangMuon' THEN 1 ELSE 0 END) AS DangMuon,
    SUM(CASE WHEN bs.TinhTrang = 'DangGiu' THEN 1 ELSE 0 END) AS DangGiu,
    COUNT(bs.MaBanSao) AS TongBanSao
FROM TaiLieu tl
LEFT JOIN BanSao bs ON bs.MaTaiLieu = tl.MaTaiLieu
GROUP BY tl.MaTaiLieu, tl.TenTaiLieu, tl.HinhThuc;

CREATE OR REPLACE VIEW vw_PhieuQuaHan AS
SELECT
    pm.Id,
    pm.MaPhieuMuon,
    pm.MaThe,
    dg.MaDocGia,
    dg.HoTen,
    dg.Email,
    bs.MaBanSao,
    tl.MaTaiLieu,
    tl.TenTaiLieu,
    pm.NgayMuon,
    pm.HanTra,
    TRUNC(SYSDATE) - pm.HanTra AS SoNgayTre
FROM PhieuMuon pm
JOIN TheThuVien t ON t.MaThe = pm.MaThe
JOIN DocGia dg ON dg.MaDocGia = t.MaDocGia
JOIN BanSao bs ON bs.MaBanSao = pm.MaBanSao
JOIN TaiLieu tl ON tl.MaTaiLieu = bs.MaTaiLieu
WHERE pm.TrangThai = 'DangMuon'
  AND pm.HanTra < TRUNC(SYSDATE);

CREATE OR REPLACE VIEW vw_TinhTrangMuon AS
SELECT
    tl.MaTaiLieu,
    tl.TenTaiLieu,
    bs.MaBanSao,
    pm.MaPhieuMuon,
    dg.HoTen AS DocGia,
    pm.NgayMuon,
    pm.HanTra,
    CASE WHEN pm.HanTra < TRUNC(SYSDATE) THEN 1 ELSE 0 END AS QuaHan,
    CASE WHEN pm.HanTra < TRUNC(SYSDATE)
         THEN TRUNC(SYSDATE) - pm.HanTra
         ELSE 0
    END AS SoNgayTre
FROM PhieuMuon pm
JOIN BanSao bs ON bs.MaBanSao = pm.MaBanSao
JOIN TaiLieu tl ON tl.MaTaiLieu = bs.MaTaiLieu
JOIN TheThuVien t ON t.MaThe = pm.MaThe
JOIN DocGia dg ON dg.MaDocGia = t.MaDocGia
WHERE pm.TrangThai = 'DangMuon';

-- =====================================================================
-- 5. STORED PROCEDURE
-- Oracle dùng DBMS_SQL.RETURN_RESULT + SYS_REFCURSOR
-- để trả result set về ứng dụng.
-- =====================================================================

CREATE OR REPLACE PROCEDURE sp_XacThucMaThe(
    p_MaThe IN VARCHAR2
) AS
    v_TrangThai TheThuVien.TrangThai%TYPE;
    v_Han       TheThuVien.HanSuDung%TYPE;
    v_Cursor    SYS_REFCURSOR;
BEGIN
    BEGIN
        SELECT TrangThai, HanSuDung
        INTO v_TrangThai, v_Han
        FROM TheThuVien
        WHERE MaThe = p_MaThe;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20001, 'Mã thẻ không tồn tại.');
    END;

    IF v_TrangThai <> 'HoatDong' THEN
        RAISE_APPLICATION_ERROR(
          -20002,
          'Thẻ đang bị khóa, báo mất hoặc đã hết hạn.'
        );
    END IF;

    IF v_Han < TRUNC(SYSDATE) THEN
        UPDATE TheThuVien
        SET TrangThai = 'HetHan'
        WHERE MaThe = p_MaThe;

        COMMIT;

        RAISE_APPLICATION_ERROR(
          -20003,
          'Thẻ thư viện đã hết hạn sử dụng.'
        );
    END IF;

    OPEN v_Cursor FOR
      SELECT
          t.MaThe,
          t.HanSuDung,
          dg.MaDocGia,
          dg.HoTen,
          dg.LoaiDocGia,
          dg.Email
      FROM TheThuVien t
      JOIN DocGia dg ON dg.MaDocGia = t.MaDocGia
      WHERE t.MaThe = p_MaThe;

    DBMS_SQL.RETURN_RESULT(v_Cursor);
END;
/

CREATE OR REPLACE PROCEDURE sp_GhiLuotTai(
    p_MaThe IN VARCHAR2,
    p_MaTaiLieu IN VARCHAR2,
    p_DiaChiIP IN VARCHAR2 DEFAULT NULL
) AS
    v_ChoPhepTai NUMBER(1);
    v_Cursor SYS_REFCURSOR;
BEGIN
    BEGIN
        SELECT ChoPhepTai
        INTO v_ChoPhepTai
        FROM TepDienTu
        WHERE MaTaiLieu = p_MaTaiLieu;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(
              -20010,
              'Tài liệu không có bản điện tử hoặc không cho phép tải về.'
            );
    END;

    IF v_ChoPhepTai <> 1 THEN
        RAISE_APPLICATION_ERROR(
          -20010,
          'Tài liệu không có bản điện tử hoặc không cho phép tải về.'
        );
    END IF;

    INSERT INTO LuotTai(MaTaiLieu, MaThe, DiaChiIP)
    VALUES (p_MaTaiLieu, p_MaThe, p_DiaChiIP);

    COMMIT;

    OPEN v_Cursor FOR
      SELECT DuongDanTep, DinhDang
      FROM TepDienTu
      WHERE MaTaiLieu = p_MaTaiLieu;

    DBMS_SQL.RETURN_RESULT(v_Cursor);
END;
/

CREATE OR REPLACE PROCEDURE sp_DangKyMuon(
    p_MaThe IN VARCHAR2,
    p_MaTaiLieu IN VARCHAR2
) AS
    v_TinhTrangThe TheThuVien.TrangThai%TYPE;
    v_Han          TheThuVien.HanSuDung%TYPE;
    v_Count        NUMBER;
    v_MaBanSao     VARCHAR2(10);
    v_Id            NUMBER;
    v_Cursor        SYS_REFCURSOR;
BEGIN
    BEGIN
        SELECT TrangThai, HanSuDung
        INTO v_TinhTrangThe, v_Han
        FROM TheThuVien
        WHERE MaThe = p_MaThe;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20001, 'Mã thẻ không tồn tại.');
    END;

    IF v_TinhTrangThe <> 'HoatDong' THEN
        RAISE_APPLICATION_ERROR(
          -20002,
          'Thẻ đang bị khóa, báo mất hoặc đã hết hạn.'
        );
    END IF;

    IF v_Han < TRUNC(SYSDATE) THEN
        UPDATE TheThuVien
        SET TrangThai = 'HetHan'
        WHERE MaThe = p_MaThe;

        COMMIT;

        RAISE_APPLICATION_ERROR(
          -20003,
          'Thẻ thư viện đã hết hạn sử dụng.'
        );
    END IF;

    SELECT COUNT(*)
    INTO v_Count
    FROM TaiLieu
    WHERE MaTaiLieu = p_MaTaiLieu
      AND HinhThuc IN ('BanIn','CaHai');

    IF v_Count = 0 THEN
        RAISE_APPLICATION_ERROR(
          -20020,
          'Chỉ đăng ký mượn được tài liệu có bản in.'
        );
    END IF;

    SELECT COUNT(*)
    INTO v_Count
    FROM PhieuMuon
    WHERE MaThe = p_MaThe
      AND TrangThai = 'DangMuon'
      AND HanTra < TRUNC(SYSDATE);

    IF v_Count > 0 THEN
        RAISE_APPLICATION_ERROR(
          -20021,
          'Độc giả còn sách quá hạn chưa trả nên không được đăng ký thêm.'
        );
    END IF;

    SELECT
      (SELECT COUNT(*)
       FROM PhieuMuon
       WHERE MaThe = p_MaThe
         AND TrangThai = 'DangMuon')
      +
      (SELECT COUNT(*)
       FROM DangKyMuon
       WHERE MaThe = p_MaThe
         AND TrangThai = 'ChoNhan')
    INTO v_Count
    FROM DUAL;

    IF v_Count >= 5 THEN
        RAISE_APPLICATION_ERROR(
          -20022,
          'Đã đạt tối đa 5 cuốn (đang mượn + đang giữ chỗ).'
        );
    END IF;

    SELECT COUNT(*)
    INTO v_Count
    FROM DangKyMuon
    WHERE MaThe = p_MaThe
      AND MaTaiLieu = p_MaTaiLieu
      AND TrangThai = 'ChoNhan';

    IF v_Count > 0 THEN
        RAISE_APPLICATION_ERROR(
          -20023,
          'Bạn đã đăng ký tài liệu này và đang chờ nhận.'
        );
    END IF;

    SELECT MIN(MaBanSao)
    INTO v_MaBanSao
    FROM BanSao
    WHERE MaTaiLieu = p_MaTaiLieu
      AND TinhTrang = 'SanSang';

    IF v_MaBanSao IS NULL THEN
        RAISE_APPLICATION_ERROR(
          -20024,
          'Tài liệu đã hết bản sao sẵn sàng.'
        );
    END IF;

    SELECT MaBanSao
    INTO v_MaBanSao
    FROM BanSao
    WHERE MaBanSao = v_MaBanSao
    FOR UPDATE;

    UPDATE BanSao
    SET TinhTrang = 'DangGiu'
    WHERE MaBanSao = v_MaBanSao;

    INSERT INTO DangKyMuon(
      MaThe, MaTaiLieu, MaBanSaoGiu, HanNhan
    )
    VALUES(
      p_MaThe,
      p_MaTaiLieu,
      v_MaBanSao,
      TRUNC(SYSDATE) + 2
    )
    RETURNING Id INTO v_Id;

    COMMIT;

    OPEN v_Cursor FOR
      SELECT MaDangKy, MaBanSaoGiu, HanNhan
      FROM DangKyMuon
      WHERE Id = v_Id;

    DBMS_SQL.RETURN_RESULT(v_Cursor);
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(
          -20025,
          'Bản sao hoặc đăng ký vừa được giữ bởi giao dịch khác.'
        );
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/

CREATE OR REPLACE PROCEDURE sp_LapPhieuMuon(
    p_MaThe IN VARCHAR2,
    p_MaBanSao IN VARCHAR2,
    p_MaThuThu IN VARCHAR2,
    p_DangKyId IN NUMBER DEFAULT NULL
) AS
    v_TinhTrang VARCHAR2(10);
    v_Count NUMBER;
    v_Id NUMBER;
    v_Cursor SYS_REFCURSOR;
BEGIN
    BEGIN
        SELECT TinhTrang
        INTO v_TinhTrang
        FROM BanSao
        WHERE MaBanSao = p_MaBanSao
        FOR UPDATE;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20030, 'Không tìm thấy bản sao.');
    END;

    IF p_DangKyId IS NOT NULL THEN
        UPDATE DangKyMuon
        SET TrangThai = 'DaNhan'
        WHERE Id = p_DangKyId
          AND MaThe = p_MaThe
          AND TrangThai = 'ChoNhan'
          AND MaBanSaoGiu = p_MaBanSao;

        IF SQL%ROWCOUNT = 0 THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(
              -20031,
              'Đăng ký không còn hiệu lực hoặc không khớp bản sao.'
            );
        END IF;
    ELSE
        IF v_TinhTrang <> 'SanSang' THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(
              -20032,
              'Bản sao không ở trạng thái sẵn sàng.'
            );
        END IF;

        SELECT COUNT(*)
        INTO v_Count
        FROM PhieuMuon
        WHERE MaThe = p_MaThe
          AND TrangThai = 'DangMuon'
          AND HanTra < TRUNC(SYSDATE);

        IF v_Count > 0 THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(
              -20021,
              'Độc giả còn sách quá hạn chưa trả.'
            );
        END IF;

        SELECT
          (SELECT COUNT(*)
           FROM PhieuMuon
           WHERE MaThe = p_MaThe
             AND TrangThai = 'DangMuon')
          +
          (SELECT COUNT(*)
           FROM DangKyMuon
           WHERE MaThe = p_MaThe
             AND TrangThai = 'ChoNhan')
        INTO v_Count
        FROM DUAL;

        IF v_Count >= 5 THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20022, 'Đã đạt tối đa 5 cuốn.');
        END IF;
    END IF;

    UPDATE BanSao
    SET TinhTrang = 'DangMuon'
    WHERE MaBanSao = p_MaBanSao;

    INSERT INTO PhieuMuon(
      MaThe,
      MaBanSao,
      DangKyId,
      MaThuThuLap,
      NgayMuon,
      HanTra
    )
    VALUES(
      p_MaThe,
      p_MaBanSao,
      p_DangKyId,
      p_MaThuThu,
      TRUNC(SYSDATE),
      TRUNC(SYSDATE) + 14
    )
    RETURNING Id INTO v_Id;

    COMMIT;

    OPEN v_Cursor FOR
      SELECT MaPhieuMuon, NgayMuon, HanTra
      FROM PhieuMuon
      WHERE Id = v_Id;

    DBMS_SQL.RETURN_RESULT(v_Cursor);
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/

CREATE OR REPLACE PROCEDURE sp_GhiNhanTraSach(
    p_MaBanSao IN VARCHAR2,
    p_MaThuThu IN VARCHAR2,
    p_TinhTrang IN VARCHAR2 DEFAULT 'NguyenVen',
    p_GhiChu IN NVARCHAR2 DEFAULT NULL
) AS
    v_Id NUMBER;
    v_HanTra DATE;
    v_MaThe VARCHAR2(12);
    v_Homnay DATE := TRUNC(SYSDATE);
    v_Cursor SYS_REFCURSOR;
BEGIN
    IF p_TinhTrang NOT IN ('NguyenVen','HuHong','Mat') THEN
        RAISE_APPLICATION_ERROR(
          -20040,
          'Tình trạng trả không hợp lệ.'
        );
    END IF;

    IF p_TinhTrang <> 'NguyenVen'
       AND TRIM(p_GhiChu) IS NULL THEN
        RAISE_APPLICATION_ERROR(
          -20041,
          'Phải nhập ghi chú khi sách hư hỏng hoặc mất.'
        );
    END IF;

    BEGIN
        SELECT Id, HanTra, MaThe
        INTO v_Id, v_HanTra, v_MaThe
        FROM PhieuMuon
        WHERE MaBanSao = p_MaBanSao
          AND TrangThai = 'DangMuon'
        FOR UPDATE;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(
              -20042,
              'Bản sao không nằm trong danh sách đang cho mượn.'
            );
    END;

    UPDATE PhieuMuon
    SET NgayTra = v_Homnay,
        MaThuThuNhan = p_MaThuThu,
        GhiChu = p_GhiChu,
        SoNgayTre =
          CASE
            WHEN v_Homnay > v_HanTra
            THEN v_Homnay - v_HanTra
            ELSE 0
          END,
        TrangThai =
          CASE p_TinhTrang
            WHEN 'NguyenVen' THEN 'DaTra'
            WHEN 'HuHong' THEN 'TraHuHong'
            ELSE 'Mat'
          END
    WHERE Id = v_Id;

    UPDATE BanSao
    SET TinhTrang =
          CASE p_TinhTrang
            WHEN 'NguyenVen' THEN 'SanSang'
            WHEN 'HuHong' THEN 'CanKiemTra'
            ELSE 'Mat'
          END,
        GhiChu = NVL(p_GhiChu, GhiChu)
    WHERE MaBanSao = p_MaBanSao;

    COMMIT;

    OPEN v_Cursor FOR
      SELECT
        pm.MaPhieuMuon,
        pm.SoNgayTre,
        pm.TrangThai,
        (
          SELECT COUNT(*)
          FROM PhieuMuon x
          WHERE x.MaThe = pm.MaThe
            AND x.TrangThai = 'DangMuon'
        ) AS ConDangGiu
      FROM PhieuMuon pm
      WHERE pm.Id = v_Id;

    DBMS_SQL.RETURN_RESULT(v_Cursor);
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/

CREATE OR REPLACE PROCEDURE sp_GuiYeuCauDatMua(
    p_MaTaiKhoan IN NUMBER,
    p_TenSach IN NVARCHAR2,
    p_TacGia IN NVARCHAR2,
    p_NamXuatBan IN NUMBER,
    p_NhaXuatBan IN NVARCHAR2 DEFAULT NULL,
    p_LyDo IN NVARCHAR2 DEFAULT NULL
) AS
    v_Id NUMBER;
    v_Count NUMBER;
    v_Cursor SYS_REFCURSOR;
BEGIN
    SELECT COUNT(*)
    INTO v_Count
    FROM TaiKhoan
    WHERE MaTaiKhoan = p_MaTaiKhoan
      AND VaiTro = 'DocGia'
      AND TrangThai = 'HoatDong';

    IF v_Count = 0 THEN
        RAISE_APPLICATION_ERROR(
          -20050,
          'Chỉ độc giả đã đăng nhập mới gửi được yêu cầu đặt mua.'
        );
    END IF;

    IF TRIM(p_TenSach) IS NULL
       OR TRIM(p_TacGia) IS NULL
       OR p_NamXuatBan IS NULL THEN
        RAISE_APPLICATION_ERROR(
          -20051,
          'Tên sách, tác giả và năm xuất bản là bắt buộc.'
        );
    END IF;

    SELECT COUNT(*)
    INTO v_Count
    FROM YeuCauDatMua
    WHERE MaTaiKhoan = p_MaTaiKhoan
      AND TrangThai = 'ChoDuyet'
      AND TenSach = p_TenSach
      AND TacGia = p_TacGia;

    IF v_Count > 0 THEN
        RAISE_APPLICATION_ERROR(
          -20052,
          'Bạn đã gửi yêu cầu này và đang chờ duyệt.'
        );
    END IF;

    INSERT INTO YeuCauDatMua(
      MaTaiKhoan,
      TenSach,
      TacGia,
      NamXuatBan,
      NhaXuatBan,
      LyDoDeNghi
    )
    VALUES(
      p_MaTaiKhoan,
      TRIM(p_TenSach),
      TRIM(p_TacGia),
      p_NamXuatBan,
      p_NhaXuatBan,
      p_LyDo
    )
    RETURNING Id INTO v_Id;

    COMMIT;

    OPEN v_Cursor FOR
      SELECT MaYeuCau
      FROM YeuCauDatMua
      WHERE Id = v_Id;

    DBMS_SQL.RETURN_RESULT(v_Cursor);
END;
/

CREATE OR REPLACE PROCEDURE sp_DuyetYeuCauDatMua(
    p_YeuCauId IN NUMBER,
    p_MaThuThu IN VARCHAR2,
    p_QuyetDinh IN VARCHAR2,
    p_GhiChu IN NVARCHAR2 DEFAULT NULL,
    p_MaTaiLieuLienKet IN VARCHAR2 DEFAULT NULL
) AS
BEGIN
    IF p_QuyetDinh NOT IN ('ChapNhan','TuChoi') THEN
        RAISE_APPLICATION_ERROR(
          -20060,
          'Quyết định phải là Chấp nhận hoặc Từ chối.'
        );
    END IF;

    IF p_QuyetDinh = 'TuChoi'
       AND TRIM(p_GhiChu) IS NULL THEN
        RAISE_APPLICATION_ERROR(
          -20061,
          'Phải nhập lý do khi từ chối.'
        );
    END IF;

    UPDATE YeuCauDatMua
    SET TrangThai = p_QuyetDinh,
        MaThuThuDuyet = p_MaThuThu,
        NgayDuyet = SYSTIMESTAMP,
        KetQuaGhiChu = p_GhiChu,
        MaTaiLieuLienKet = p_MaTaiLieuLienKet
    WHERE Id = p_YeuCauId
      AND TrangThai = 'ChoDuyet';

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(
          -20062,
          'Yêu cầu đã được một thủ thư khác xử lý hoặc không tồn tại.'
        );
    END IF;

    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE sp_HuyDangKyHetHan AS
    v_Count NUMBER := 0;
    v_Cursor SYS_REFCURSOR;
BEGIN
    FOR r IN (
      SELECT Id, MaBanSaoGiu
      FROM DangKyMuon
      WHERE TrangThai = 'ChoNhan'
        AND HanNhan < TRUNC(SYSDATE)
      FOR UPDATE
    )
    LOOP
      UPDATE DangKyMuon
      SET TrangThai = 'HetHan'
      WHERE Id = r.Id;

      UPDATE BanSao
      SET TinhTrang = 'SanSang'
      WHERE MaBanSao = r.MaBanSaoGiu
        AND TinhTrang = 'DangGiu';

      v_Count := v_Count + 1;
    END LOOP;

    COMMIT;

    OPEN v_Cursor FOR
      SELECT v_Count AS SoDangKyHuy
      FROM DUAL;

    DBMS_SQL.RETURN_RESULT(v_Cursor);
END;
/

CREATE OR REPLACE PROCEDURE sp_QuetNhacHanTra(
    p_SoNgayTruoc IN NUMBER DEFAULT 3
) AS
    v_NgayHan DATE := TRUNC(SYSDATE) + p_SoNgayTruoc;
    v_NhatKy NUMBER;
    v_Count NUMBER;
    v_Cursor SYS_REFCURSOR;
BEGIN
    INSERT INTO NhatKyLapLich(TenCongViec, BatDau)
    VALUES ('NhacHanTra', SYSTIMESTAMP)
    RETURNING Id INTO v_NhatKy;

    INSERT INTO EmailNhacHan(
      PhieuMuonId,
      DiaChiNhan,
      TieuDe,
      NoiDung
    )
    SELECT
      pm.Id,
      dg.Email,
      N'[Thư viện] Nhắc hạn trả sách ' || pm.MaPhieuMuon,
      N'Chào ' || dg.HoTen ||
      N', cuốn "' || tl.TenTaiLieu ||
      N'" (bản sao ' || bs.MaBanSao ||
      N') đến hạn trả vào ngày ' ||
      TO_CHAR(pm.HanTra,'DD/MM/YYYY') ||
      N'. Vui lòng hoàn trả đúng hạn. Trân trọng!'
    FROM PhieuMuon pm
    JOIN TheThuVien t ON t.MaThe = pm.MaThe
    JOIN DocGia dg ON dg.MaDocGia = t.MaDocGia
    JOIN BanSao bs ON bs.MaBanSao = pm.MaBanSao
    JOIN TaiLieu tl ON tl.MaTaiLieu = bs.MaTaiLieu
    WHERE pm.TrangThai = 'DangMuon'
      AND pm.HanTra = v_NgayHan
      AND NOT EXISTS (
        SELECT 1
        FROM EmailNhacHan e
        WHERE e.PhieuMuonId = pm.Id
      );

    v_Count := SQL%ROWCOUNT;

    UPDATE NhatKyLapLich
    SET SoBanGhiQuet = v_Count
    WHERE Id = v_NhatKy;

    COMMIT;

    OPEN v_Cursor FOR
      SELECT
        e.Id,
        e.MaEmail,
        e.DiaChiNhan,
        e.TieuDe,
        e.NoiDung,
        e.SoLanThu,
        v_NhatKy AS NhatKyId
      FROM EmailNhacHan e
      WHERE e.TrangThai = 'ChoGui'
         OR (e.TrangThai = 'Loi' AND e.SoLanThu < 3);

    DBMS_SQL.RETURN_RESULT(v_Cursor);
END;
/

CREATE OR REPLACE PROCEDURE sp_CapNhatKetQuaEmail(
    p_EmailId IN NUMBER,
    p_ThanhCong IN NUMBER,
    p_Loi IN NVARCHAR2 DEFAULT NULL,
    p_NhatKyId IN NUMBER DEFAULT NULL
) AS
BEGIN
    UPDATE EmailNhacHan
    SET SoLanThu = SoLanThu + 1,
        TrangThai =
          CASE
            WHEN p_ThanhCong = 1 THEN 'DaGui'
            ELSE 'Loi'
          END,
        ThoiDiemGui =
          CASE
            WHEN p_ThanhCong = 1 THEN SYSTIMESTAMP
            ELSE ThoiDiemGui
          END,
        LoiGanNhat = p_Loi
    WHERE Id = p_EmailId
      AND SoLanThu < 3;

    IF p_NhatKyId IS NOT NULL THEN
        UPDATE NhatKyLapLich
        SET SoThanhCong =
              SoThanhCong
              + CASE WHEN p_ThanhCong = 1 THEN 1 ELSE 0 END,
            SoLoi =
              SoLoi
              + CASE WHEN p_ThanhCong = 1 THEN 0 ELSE 1 END,
            KetThuc = SYSTIMESTAMP
        WHERE Id = p_NhatKyId;
    END IF;

    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE sp_ThongKeTongHop(
    p_TuNgay IN DATE,
    p_DenNgay IN DATE
) AS
    v_TuNgay DATE := TRUNC(p_TuNgay);
    v_DenNgay DATE := TRUNC(p_DenNgay);
    v_Tmp DATE;
    v_Cursor SYS_REFCURSOR;
BEGIN
    IF v_TuNgay > v_DenNgay THEN
        v_Tmp := v_TuNgay;
        v_TuNgay := v_DenNgay;
        v_DenNgay := v_Tmp;
    END IF;

    -- 1. KPI
    OPEN v_Cursor FOR
      SELECT
        (SELECT COUNT(*)
         FROM PhieuMuon
         WHERE NgayMuon BETWEEN v_TuNgay AND v_DenNgay) AS LuotMuon,
        (SELECT COUNT(*) FROM vw_PhieuQuaHan) AS DangQuaHan,
        (SELECT COUNT(*)
         FROM LuotTai
         WHERE TRUNC(CAST(ThoiDiem AS DATE))
               BETWEEN v_TuNgay AND v_DenNgay) AS LuotTai,
        (SELECT COUNT(*)
         FROM YeuCauDatMua
         WHERE TRUNC(CAST(NgayGui AS DATE))
               BETWEEN v_TuNgay AND v_DenNgay) AS YeuCauDatMua,
        (SELECT COUNT(*)
         FROM EmailNhacHan
         WHERE TrangThai = 'DaGui'
           AND TRUNC(CAST(ThoiDiemGui AS DATE))
               BETWEEN v_TuNgay AND v_DenNgay) AS EmailDaGui
      FROM DUAL;

    DBMS_SQL.RETURN_RESULT(v_Cursor);

    -- 2. Lượt mượn theo chủ đề
    OPEN v_Cursor FOR
      SELECT
        cd.TenChuDe,
        COUNT(pm.Id) AS LuotMuon
      FROM ChuDe cd
      LEFT JOIN TaiLieu tl ON tl.MaChuDe = cd.MaChuDe
      LEFT JOIN BanSao bs ON bs.MaTaiLieu = tl.MaTaiLieu
      LEFT JOIN PhieuMuon pm
        ON pm.MaBanSao = bs.MaBanSao
       AND pm.NgayMuon BETWEEN v_TuNgay AND v_DenNgay
      GROUP BY cd.TenChuDe
      ORDER BY LuotMuon DESC;

    DBMS_SQL.RETURN_RESULT(v_Cursor);

    -- 3. Danh sách quá hạn
    OPEN v_Cursor FOR
      SELECT
        q.*,
        CASE
          WHEN e.TrangThai = 'DaGui' THEN N'Có'
          ELSE N'Không'
        END AS DaNhac
      FROM vw_PhieuQuaHan q
      LEFT JOIN EmailNhacHan e ON e.PhieuMuonId = q.Id
      ORDER BY q.SoNgayTre DESC;

    DBMS_SQL.RETURN_RESULT(v_Cursor);

    -- 4. Top 10 tài liệu được tải
    OPEN v_Cursor FOR
      SELECT *
      FROM (
        SELECT
          tl.MaTaiLieu,
          tl.TenTaiLieu,
          COUNT(*) AS LuotTai
        FROM LuotTai lt
        JOIN TaiLieu tl ON tl.MaTaiLieu = lt.MaTaiLieu
        WHERE TRUNC(CAST(lt.ThoiDiem AS DATE))
              BETWEEN v_TuNgay AND v_DenNgay
        GROUP BY tl.MaTaiLieu, tl.TenTaiLieu
        ORDER BY LuotTai DESC
      )
      FETCH FIRST 10 ROWS ONLY;

    DBMS_SQL.RETURN_RESULT(v_Cursor);

    -- 5. Đặt mua theo trạng thái
    OPEN v_Cursor FOR
      SELECT TrangThai, COUNT(*) AS SoYeuCau
      FROM YeuCauDatMua
      WHERE TRUNC(CAST(NgayGui AS DATE))
            BETWEEN v_TuNgay AND v_DenNgay
      GROUP BY TrangThai;

    DBMS_SQL.RETURN_RESULT(v_Cursor);
END;
/

-- =====================================================================
-- 6. DỮ LIỆU MẪU
-- =====================================================================

INSERT INTO ThuThu(
  MaThuThu, HoTen, Email, SoDienThoai, ChucVu
) VALUES (
  'TT01', N'Lê Thị Hoa', 'hoa.lt@hutech.edu.vn',
  '0901000001', N'Trưởng thư viện'
);

INSERT INTO ThuThu(
  MaThuThu, HoTen, Email, SoDienThoai, ChucVu
) VALUES (
  'TT02', N'Võ Minh Khoa', 'khoa.vm@hutech.edu.vn',
  '0901000002', N'Thủ thư'
);

INSERT INTO DocGia(
  MaDocGia, HoTen, LoaiDocGia, DonVi, NgaySinh,
  Email, SoDienThoai
) VALUES (
  'DG0001', N'Nguyễn Văn An', 'SinhVien', N'12_CNPM2',
  DATE '2006-03-12', 'an.nv@hutech.edu.vn', '0912000001'
);

INSERT INTO DocGia(
  MaDocGia, HoTen, LoaiDocGia, DonVi, NgaySinh,
  Email, SoDienThoai
) VALUES (
  'DG0002', N'Trần Thị Bình', 'GiangVien', N'Khoa CNTT',
  DATE '1985-07-20', 'binh.tt@hutech.edu.vn', '0912000002'
);

INSERT INTO DocGia(
  MaDocGia, HoTen, LoaiDocGia, DonVi, NgaySinh,
  Email, SoDienThoai
) VALUES (
  'DG0003', N'Lê Minh Châu', 'SinhVien', N'12_CNPM1',
  DATE '2006-11-02', 'chau.lm@hutech.edu.vn', '0912000003'
);

INSERT INTO DocGia(
  MaDocGia, HoTen, LoaiDocGia, DonVi, NgaySinh,
  Email, SoDienThoai
) VALUES (
  'DG0004', N'Phạm Quốc Duy', 'NhanVien', N'Phòng Đào tạo',
  DATE '1990-01-15', 'duy.pq@hutech.edu.vn', '0912000004'
);

INSERT INTO TheThuVien(
  MaThe, MaDocGia, NgayCap, HanSuDung, TrangThai
) VALUES (
  'TV2026000123','DG0001',
  DATE '2026-09-01', DATE '2027-09-30', 'HoatDong'
);

INSERT INTO TheThuVien(
  MaThe, MaDocGia, NgayCap, HanSuDung, TrangThai
) VALUES (
  'TV2025000045','DG0002',
  DATE '2025-03-15', DATE '2027-03-15', 'HoatDong'
);

INSERT INTO TheThuVien(
  MaThe, MaDocGia, NgayCap, HanSuDung, TrangThai
) VALUES (
  'TV2026000150','DG0003',
  DATE '2026-01-10', DATE '2027-01-10', 'HoatDong'
);

INSERT INTO TheThuVien(
  MaThe, MaDocGia, NgayCap, HanSuDung, TrangThai
) VALUES (
  'TV2024000010','DG0004',
  DATE '2024-01-01', DATE '2025-01-01', 'HetHan'
);

-- Mật khẩu mẫu: Thuvien@123
-- Hash giữ theo semantics SQL Server:
-- SHA2_256(SALT + UTF-16LE('Thuvien@123'))
INSERT INTO TaiKhoan(
  TenDangNhap, MatKhauHash, MatKhauSalt,
  VaiTro, MaDocGia, MaThuThu
) VALUES (
  'hoa.lt',
  HEXTORAW('866DA52251D16E479B7AFE5CBF4597B9E461542D068113C923C5197F355DD4BF'),
  HEXTORAW('0F1E2D3C4B5A69788796A5B4C3D2E1F0'),
  'ThuThu', NULL, 'TT01'
);

INSERT INTO TaiKhoan(
  TenDangNhap, MatKhauHash, MatKhauSalt,
  VaiTro, MaDocGia, MaThuThu
) VALUES (
  'khoa.vm',
  HEXTORAW('866DA52251D16E479B7AFE5CBF4597B9E461542D068113C923C5197F355DD4BF'),
  HEXTORAW('0F1E2D3C4B5A69788796A5B4C3D2E1F0'),
  'ThuThu', NULL, 'TT02'
);

INSERT INTO TaiKhoan(
  TenDangNhap, MatKhauHash, MatKhauSalt,
  VaiTro, MaDocGia, MaThuThu
) VALUES (
  'an.nv',
  HEXTORAW('866DA52251D16E479B7AFE5CBF4597B9E461542D068113C923C5197F355DD4BF'),
  HEXTORAW('0F1E2D3C4B5A69788796A5B4C3D2E1F0'),
  'DocGia', 'DG0001', NULL
);

INSERT INTO TaiKhoan(
  TenDangNhap, MatKhauHash, MatKhauSalt,
  VaiTro, MaDocGia, MaThuThu
) VALUES (
  'binh.tt',
  HEXTORAW('866DA52251D16E479B7AFE5CBF4597B9E461542D068113C923C5197F355DD4BF'),
  HEXTORAW('0F1E2D3C4B5A69788796A5B4C3D2E1F0'),
  'DocGia', 'DG0002', NULL
);

INSERT INTO ChuDe VALUES (
  'CD01', N'Công nghệ thông tin',
  N'Lập trình, CSDL, mạng máy tính'
);

INSERT INTO ChuDe VALUES (
  'CD02', N'Kinh tế',
  N'Quản trị, tài chính, marketing'
);

INSERT INTO ChuDe VALUES (
  'CD03', N'Ngoại ngữ', NULL
);

INSERT INTO TacGia VALUES (
  'TG01', N'Phạm Hữu Khang', NULL
);

INSERT INTO TacGia VALUES (
  'TG02', N'Đặng Văn Đức', NULL
);

INSERT INTO TacGia VALUES (
  'TG03', N'Đỗ Trung Tuấn', NULL
);

INSERT INTO TacGia VALUES (
  'TG04', N'Robert C. Martin', NULL
);

INSERT INTO NhaXuatBan VALUES (
  'NXB01', N'NXB Lao động',
  N'175 Giảng Võ, Hà Nội', '02438515380'
);

INSERT INTO NhaXuatBan VALUES (
  'NXB02', N'NXB Giáo dục',
  N'81 Trần Hưng Đạo, Hà Nội', '02438220801'
);

INSERT INTO NhaXuatBan VALUES (
  'NXB03', N'NXB ĐHQG TP.HCM',
  N'Linh Trung, Thủ Đức, TP.HCM', '02837242181'
);

INSERT INTO TaiLieu VALUES (
  'TL0001', N'Lập trình C# căn bản',
  'Sach', 'BanIn', 'CD01', 'NXB01', 2019,
  N'Nhập môn C# và .NET', SYSTIMESTAMP, NULL
);

INSERT INTO TaiLieu VALUES (
  'TL0002', N'Phân tích thiết kế hướng đối tượng',
  'Sach', 'CaHai', 'CD01', 'NXB02', 2021,
  N'UML và quy trình phân tích', SYSTIMESTAMP, NULL
);

INSERT INTO TaiLieu VALUES (
  'TL0003', N'Cơ sở dữ liệu',
  'Sach', 'DienTu', 'CD01', 'NXB03', 2020,
  N'Mô hình quan hệ, SQL', SYSTIMESTAMP, NULL
);

INSERT INTO TaiLieu VALUES (
  'TL0004', N'Clean Architecture',
  'Sach', 'DienTu', 'CD01', NULL, 2017,
  N'Bổ sung từ yêu cầu YC000001', SYSTIMESTAMP, NULL
);

INSERT INTO TaiLieu_TacGia VALUES ('TL0001','TG01',1);
INSERT INTO TaiLieu_TacGia VALUES ('TL0002','TG02',1);
INSERT INTO TaiLieu_TacGia VALUES ('TL0003','TG03',1);
INSERT INTO TaiLieu_TacGia VALUES ('TL0004','TG04',1);

INSERT INTO TepDienTu VALUES (
  'TL0002', N'\\fileserver\ebook\TL0002.pdf',
  'PDF', 12.50, 1
);

INSERT INTO TepDienTu VALUES (
  'TL0003', N'\\fileserver\ebook\TL0003.pdf',
  'PDF', 8.20, 1
);

INSERT INTO TepDienTu VALUES (
  'TL0004', N'\\fileserver\ebook\TL0004.epub',
  'EPUB', 3.10, 0
);

INSERT INTO BanSao VALUES (
  'BS000011','TL0001','A1',SYSDATE,'SanSang',NULL
);

INSERT INTO BanSao VALUES (
  'BS000012','TL0001','A1',SYSDATE,'SanSang',NULL
);

INSERT INTO BanSao VALUES (
  'BS000013','TL0001','A1',SYSDATE,'SanSang',NULL
);

INSERT INTO BanSao VALUES (
  'BS000021','TL0002','A2',SYSDATE,'SanSang',NULL
);

INSERT INTO BanSao VALUES (
  'BS000022','TL0002','A2',SYSDATE,'SanSang',NULL
);

-- Một phiếu đang mượn còn 3 ngày đến hạn
-- và một phiếu quá hạn.
INSERT INTO PhieuMuon(
  MaThe, MaBanSao, MaThuThuLap, NgayMuon, HanTra
) VALUES (
  'TV2026000123','BS000012','TT01',
  TRUNC(SYSDATE)-11, TRUNC(SYSDATE)+3
);

INSERT INTO PhieuMuon(
  MaThe, MaBanSao, MaThuThuLap, NgayMuon, HanTra
) VALUES (
  'TV2026000150','BS000022','TT02',
  TRUNC(SYSDATE)-17, TRUNC(SYSDATE)-3
);

UPDATE BanSao
SET TinhTrang = 'DangMuon'
WHERE MaBanSao IN ('BS000012','BS000022');

INSERT INTO YeuCauDatMua(
  MaTaiKhoan, TenSach, TacGia, NamXuatBan,
  LyDoDeNghi, TrangThai, MaThuThuDuyet,
  NgayDuyet, KetQuaGhiChu, MaTaiLieuLienKet
)
SELECT
  MaTaiKhoan,
  N'Clean Architecture',
  N'Robert C. Martin',
  2017,
  N'Phục vụ môn Kiến trúc phần mềm',
  'ChapNhan',
  'TT01',
  SYSTIMESTAMP,
  N'Đã bổ sung',
  'TL0004'
FROM TaiKhoan
WHERE TenDangNhap = 'an.nv';

INSERT INTO YeuCauDatMua(
  MaTaiKhoan, TenSach, TacGia, NamXuatBan, LyDoDeNghi
)
SELECT
  MaTaiKhoan,
  N'Domain-Driven Design',
  N'Eric Evans',
  2003,
  N'Tham khảo đồ án'
FROM TaiKhoan
WHERE TenDangNhap = 'an.nv';

COMMIT;

-- =====================================================================
-- 7. KIỂM TRA
-- =====================================================================

SELECT table_name
FROM user_tables
ORDER BY table_name;

SELECT object_name, object_type, status
FROM user_objects
WHERE object_type IN ('TABLE','VIEW','PROCEDURE')
ORDER BY object_type, object_name;

SELECT COUNT(*) AS TaiLieu FROM TaiLieu;
SELECT MaPhieuMuon, HanTra FROM PhieuMuon;

SELECT * FROM vw_TonKho;
SELECT * FROM vw_PhieuQuaHan;
SELECT * FROM vw_TinhTrangMuon;

-- TEST PROCEDURE:
-- EXEC sp_XacThucMaThe('TV2026000123');
-- EXEC sp_GhiLuotTai('TV2026000123','TL0002','127.0.0.1');
-- EXEC sp_DangKyMuon('TV2026000123','TL0001');
-- EXEC sp_LapPhieuMuon('TV2026000123','BS000011','TT01',NULL);
-- EXEC sp_GhiNhanTraSach('BS000022','TT01','HuHong',N'Rách bìa');
-- EXEC sp_QuetNhacHanTra(3);
-- EXEC sp_ThongKeTongHop(DATE '2026-09-30',DATE '2026-09-01');

PROMPT [3/3] HOAN TAT SCRIPT.
