
SET DEFINE OFF;

BEGIN
  FOR r IN (SELECT table_name FROM user_tables WHERE table_name IN (
      'CHITIETKIEMTRATIENNGHI','PHIEUKIEMTRATIENNGHI','GIAODICHCOC','LICHSUGIAPHONG','TAIKHOAN'))
  LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || r.table_name || ' CASCADE CONSTRAINTS PURGE';
  END LOOP;
END;
/

CREATE TABLE TaiKhoan (
    TenDangNhap      VARCHAR2(50)  NOT NULL,
    MaNV             VARCHAR2(20)  NOT NULL,
    MatKhauHash      RAW(32)       NOT NULL,
    MatKhauSalt      RAW(16)       NOT NULL,
    TrangThai        VARCHAR2(10)  DEFAULT 'HoatDong' NOT NULL,
    SoLanSaiLienTiep NUMBER(3)     DEFAULT 0 NOT NULL,
    LanDangNhapCuoi  TIMESTAMP(0),
    CONSTRAINT PK_TaiKhoan PRIMARY KEY (TenDangNhap),
    CONSTRAINT UQ_TaiKhoan_NV UNIQUE (MaNV),
    CONSTRAINT FK_TaiKhoan_NV FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV),
    CONSTRAINT CK_TaiKhoan_TrangThai CHECK (TrangThai IN ('HoatDong', 'TamKhoa'))
);

CREATE TABLE LichSuGiaPhong (
    Id         NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    SoPhong    VARCHAR2(20) NOT NULL,
    TuNgay     DATE         NOT NULL,
    DenNgay    DATE,
    DonGiaNgay NUMBER(18,2) NOT NULL,
    CONSTRAINT PK_LichSuGiaPhong PRIMARY KEY (Id),
    CONSTRAINT FK_LSGia_Phong FOREIGN KEY (SoPhong) REFERENCES Phong(SoPhong),
    CONSTRAINT CK_LSGia_Ngay CHECK (DenNgay IS NULL OR DenNgay >= TuNgay),
    CONSTRAINT CK_LSGia_DonGia CHECK (DonGiaNgay >= 0)
);

CREATE TABLE GiaoDichCoc (
    Id         NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    SoPhieuDat VARCHAR2(30)  NOT NULL,
    NgayGD     DATE          NOT NULL,
    LoaiGD     NVARCHAR2(20) NOT NULL,
    SoTien     NUMBER(18,2)  NOT NULL,
    GhiChu     NVARCHAR2(250),
    CONSTRAINT PK_GiaoDichCoc PRIMARY KEY (Id),
    CONSTRAINT FK_GDCoc_PhieuDat FOREIGN KEY (SoPhieuDat) REFERENCES PhieuDatPhong(SoPhieuDat),
    CONSTRAINT CK_GDCoc_Loai CHECK (LoaiGD IN (N'Thu cọc', N'Trừ vào hóa đơn', N'Hoàn cọc', N'Mất cọc')),
    CONSTRAINT CK_GDCoc_SoTien CHECK (SoTien > 0)
);

CREATE TABLE PhieuKiemTraTienNghi (
    SoPhieuKT  VARCHAR2(30) NOT NULL,
    SoPhieuDat VARCHAR2(30) NOT NULL,
    SoPhong    VARCHAR2(20) NOT NULL,
    NgayKiemTra DATE        NOT NULL,
    MaNV       VARCHAR2(20) NOT NULL,
    KetLuan    NVARCHAR2(250),
    CONSTRAINT PK_PhieuKiemTra PRIMARY KEY (SoPhieuKT),
    CONSTRAINT FK_PhieuKT_CTDat FOREIGN KEY (SoPhieuDat, SoPhong)
        REFERENCES ChiTietDatPhong(SoPhieuDat, SoPhong),
    CONSTRAINT FK_PhieuKT_NV FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV)
);

CREATE TABLE ChiTietKiemTraTienNghi (
    SoPhieuKT  VARCHAR2(30)  NOT NULL,
    MaTienNghi VARCHAR2(30)  NOT NULL,
    TinhTrang  NVARCHAR2(100) NOT NULL,
    CoHuHong   NUMBER(1)     DEFAULT 0 NOT NULL,
    CONSTRAINT PK_CTKiemTra PRIMARY KEY (SoPhieuKT, MaTienNghi),
    CONSTRAINT FK_CTKT_Phieu FOREIGN KEY (SoPhieuKT) REFERENCES PhieuKiemTraTienNghi(SoPhieuKT),
    CONSTRAINT FK_CTKT_TienNghi FOREIGN KEY (MaTienNghi) REFERENCES TienNghi(MaTienNghi),
    CONSTRAINT CK_CTKT_CoHuHong CHECK (CoHuHong IN (0, 1))
);

COMMIT;

SELECT table_name FROM user_tables
WHERE table_name IN ('TAIKHOAN','LICHSUGIAPHONG','GIAODICHCOC','PHIEUKIEMTRATIENNGHI','CHITIETKIEMTRATIENNGHI')
ORDER BY table_name;

PROMPT HOAN TAT MODULE MO RONG.
